### PR TITLE
Port the build to Jenkins pipeline (CONJ-4442 and CONJ-4443)

### PR DESCRIPTION
**Pull request by dividedmind**
The goal was to port the build job to a pipeline with minimal changes in existing scripts. To that end `jenkins.sh` script is left in and the job steps call out to its various functions, while still preserving the ability to run everything by just running `./jenkins.sh`.

https://jenkins.conjur.net/job/conjur-cookbooks--conjur/job/jenkins-pipeline/2/

### CODE REVIEW

**Comment by dividedmind** [comment]
https://jenkins.conjur.net/blue/organizations/jenkins/conjur-cookbooks--conjur/detail/jenkins-pipeline/3/pipeline

**Comment by jvanderhoof** [comment]
What do you think about following the pattern we're using in other projects, where each step has a single file?  It's a bit pedantic, as it's just moving code from a single file to multiple files, but it feels valuable to have a standard pattern for our pipelines.

**Comment by dividedmind** [comment]
I'm not a huge fan of that particular pattern: it litters that top dir with many related files; it's nicer to have a single point of entry where you can see what's available at a glance, as opposed to trying to visually filter the top `ls`; since there can be unrelated shell scripts (like for example `mkimage.sh` in the `appliance` repo) it's even harder to say which are 'steps' and which are utilities; and code sharing is a pain (while adding to the aforementioned complaints), encouraging code duplication. All that makes the top dir and steps seem messy and confusing in my view. I'm all for convention, but would rather see a single Makefile or Rakefile be its base.

However if it IS a convention we want to follow, I sure can (grudgingly ;) ) make this repo follow it. Your call, despite the rant I don't care that much! :)

**Comment by dividedmind** [comment]
Added test kitchen run:
https://jenkins.conjur.net/blue/organizations/jenkins/conjur-cookbooks--conjur/detail/jenkins-pipeline/6/pipeline

**Comment by jvanderhoof** [comment]
Solid argument :).  Thinking about it that way, Rake does have some appeal (but would add a dependency to Jenkins) considering it's Ruby.
```
rake build
rake test
rake publish
```

**Comment by apotterri** [comment]
Actually, there is a single point of entry in all the other projects: the Jenkinsfile. It tells you which scripts are steps. That's the convention we've followed (nearly?) everywhere. 

Having said that, I don't see a strong argument for switching to a bunch of scripts, rather than this style.

I'm not a fan of Makefiles, though. I've always found them arcane, and appreciated other people's complaints about how hard they are to understand and maintain. It feels like there are tools that are better, especially when you're not actually creating artifacts in the filesystem.

The Makefile here is written, though, so I guess it makes sense to leave it for now.

**Pull request merged**
